model_name_or_path: /data/models/Qwen2.5-7B-Instruct
adapter_name_or_path: ../datamix/sft_results/compression_ratio_config1/train
template: qwen
finetuning_type: lora

### export
export_dir: ../datamix/sft_results/compression_ratio_config1/merge
export_size: 32
export_device: cpu
export_legacy_format: false
