model_name_or_path: {path_to_base_model}
adapter_name_or_path: {path_to_trained_model}
template: qwen
finetuning_type: lora

### export
export_dir: {path_to_merged_model}
export_size: 32
export_device: cpu
export_legacy_format: false
