### model
model_name_or_path: {path_to_trained_model}
template: qwen
trust_remote_code: true

### export
export_dir: {path_to_merged_model}
export_size: 32
export_device: cpu  # choices: [cpu, auto]
export_legacy_format: false
