### model
model_name_or_path: ../datamix/sft_results/compression_ratio_config2/train
template: qwen
trust_remote_code: true

### export
export_dir: ../datamix/sft_results/compression_ratio_config2/merge
export_size: 32
export_device: cpu  # choices: [cpu, auto]
export_legacy_format: false
